apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-08-13T05:52:48Z"
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: default
  resourceVersion: "13351"
  uid: 5f4a0331-af8c-4459-88cb-fd0a527f42cb
spec:
  clusterIP: 10.100.85.95
  clusterIPs:
  - 10.100.85.95
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32311
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-deployment
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
